server:
  port: 8081
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

canal.conf:
  mode: tcp # kafka rocketMQ
  canalServerHost: 127.0.0.1:11111
  #  zookeeperHosts: slave1:2181
  #  mqServers: 127.0.0.1:9092 #or rocketmq
  #  flatMessage: true
  batchSize: 500
  syncBatchSize: 1000
  retries: 0
  timeout:
  #  accessKey:
  #  secretKey:
  srcDataSources:
    defaultDS:
      url: jdbc:mysql://localhost:3306/order_center?useUnicode=true
      username: root
      password: 123456
    payCenter:
      url: jdbc:mysql://localhost:3306/pay_center?useUnicode=true
      username: root
      password: 123456
  canalAdapters:
    - instance: xy # canal instance Name or mq topic name
      groups:
        - groupId: g1
          outerAdapters:
            - name: logger
            - name: es7
#              hosts: es-cn-n6w1wp9xp0035mea0.elasticsearch.aliyuncs.com:9200 # 127.0.0.1:9200 for rest mode
              hosts: 127.0.0.1:9200
              properties:
                mode: rest # or rest
#                security.auth: elastic:Tstyllr@yzhxcql #  only used for rest mode
#                cluster.name: es-cn-n6w1wp9xp0035mea0
                cluster.name: elasticsearch
#    - instance: example # canal instance Name or mq topic name
#      groups:
#        - groupId: g2
#          outerAdapters:
#            - name: logger




#      - name: rdb
#        key: mysql1
#        properties:
#          jdbc.driverClassName: com.mysql.jdbc.Driver
#          jdbc.url: jdbc:mysql://127.0.0.1:3306/mytest2?useUnicode=true
#          jdbc.username: root
#          jdbc.password: 121212
#      - name: rdb
#        key: oracle1
#        properties:
#          jdbc.driverClassName: oracle.jdbc.OracleDriver
#          jdbc.url: jdbc:oracle:thin:@localhost:49161:XE
#          jdbc.username: mytest
#          jdbc.password: m121212
#      - name: rdb
#        key: postgres1
#        properties:
#          jdbc.driverClassName: org.postgresql.Driver
#          jdbc.url: jdbc:postgresql://localhost:5432/postgres
#          jdbc.username: postgres
#          jdbc.password: 121212
#          threads: 1
#          commitSize: 3000
#      - name: hbase
#        properties:
#          hbase.zookeeper.quorum: 127.0.0.1
#          hbase.zookeeper.property.clientPort: 2181
#          zookeeper.znode.parent: /hbase

