dataSourceKey: defaultDS        # 源数据源的key, 对应上面配置的srcDataSources中的值
#outerAdapterKey: es1     # 对应application.yml中es配置的key
destination: example            # cannal的instance或者MQ的topic
groupId: g1                   # 对应MQ模式下的groupId, 只会同步对应groupId的数据
esMapping:
  _index: test_canal_join           # es 的索引名称
  #  _type: _doc                   # es 的type名称, es7下无需配置此项
  _id: _id                      # es 的_id, 如果不配置该项必须配置下面的pk项_id则会由es自动分配
  #  pk: id                       # 如果不需要_id, 则需要指定一个属性为主键属性
  # sql映射
  sql: "SELECT cd.plate_number plateNumber,  cd.sum_capacity_tonnage sumCapacityTonnage, cd.priority priority,
   cd.capacity_tonnage capacityTonnage, cd.axle_number axleNumber, cd.id id, cd.type TYPE, cd.created_date createdDate,
   cd.car_id carId, cd.STATUS STATUS, cd.update_user_nick updateUserNick, cd.update_user_name updateUserName,
   cd.update_date_time updateDateTime, ule.NAME driverName, ule.mobile driverMobile, uleowner.mobile AS ownerMobile,
   uleowner.NAME AS boss, crr.reason priorityReason
   FROM car_driving AS cd LEFT  JOIN user_little ule ON cd.member_id=ule.user_id
   LEFT JOIN car c ON cd.car_id=c.id
   LEFT  JOIN user_little uleowner ON c.owner_id=uleowner.user_id
   LEFT JOIN car_reject_reason crr ON cd.priority_reason_id=crr.id "
  sqlConditionFileds:
    car_driving: cd.id
    car: c.id
    user_little: [ule.user_id,uleowner.user_id]

  mainTab: sys_user
  #sql: "SELECT id as _id,login_name,name,email,phone FROM sys_user"
#  objFields:
#    _labels: array:;           # 数组或者对象属性, array:; 代表以;字段里面是以;分隔的
#    _obj: object               # json对象
#  etlCondition: "where a.c_time>='{0}'"     # etl 的条件参数
#  commitBatch: 3000                         # 提交批大小